create table produtos (
  id bigint primary key generated always as identity,
  created_at timestamptz default now(),
  nome text not null,
  peso text not null,
  preco numeric not null,
  preco_promocional numeric,
  descricao text not null,
  imagem_url text,
  updated_at timestamptz default now(),
  subcategoria_id bigint references subcategorias(id) on delete set null
);

-- Criar política de segurança para permitir acesso público
alter table produtos enable row level security;

create policy "Permitir acesso público aos produtos"
  on produtos for all
  using (true)
  with check (true);

-- Remover bucket se existir
drop policy if exists "Imagens públicas" on storage.objects;
drop bucket if exists produtos-imagens;

-- Criar bucket para as imagens
insert into storage.buckets (id, name, public) 
values ('produtos-imagens', 'produtos-imagens', true);

-- Criar política para o bucket de imagens
create policy "Imagens públicas"
  on storage.objects for all
  using ( bucket_id = 'produtos-imagens' )
  with check ( bucket_id = 'produtos-imagens' );

-- Permitir upload anônimo
create policy "Upload público"
  on storage.objects for insert
  with check ( bucket_id = 'produtos-imagens' );

-- Permitir update anônimo
create policy "Update público"
  on storage.objects for update
  using ( bucket_id = 'produtos-imagens' );

-- Permitir delete anônimo
create policy "Delete público"
  on storage.objects for delete
  using ( bucket_id = 'produtos-imagens' );

-- Criar tabela de categorias
create table categorias (
  id bigint primary key generated always as identity,
  nome text not null,
  created_at timestamptz default now()
);

-- Criar tabela de subcategorias
create table subcategorias (
  id bigint primary key generated always as identity,
  nome text not null,
  categoria_id bigint references categorias(id) on delete cascade,
  created_at timestamptz default now()
);

-- Políticas de segurança para categorias
alter table categorias enable row level security;
create policy "Permitir acesso público às categorias"
  on categorias for all
  using (true)
  with check (true);

-- Políticas de segurança para subcategorias
alter table subcategorias enable row level security;
create policy "Permitir acesso público às subcategorias"
  on subcategorias for all
  using (true)
  with check (true);

-- Criar tabela de pedidos
create table pedidos (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text not null,
  endereco text not null,
  observacoes text,
  itens jsonb not null,
  total decimal(10,2) not null,
  status text not null default 'pendente',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Políticas de segurança para pedidos
create policy "Pedidos são visíveis para todos"
  on pedidos for select
  using ( true );

create policy "Qualquer um pode criar pedidos"
  on pedidos for insert
  with check ( true );

-- Habilitar RLS
alter table pedidos enable row level security;

-- Criar índices
create index pedidos_created_at_idx on pedidos(created_at desc);
create index pedidos_status_idx on pedidos(status); 